---
title: "bootstrapsubplots"
author: "Eleanor"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```
Full Data
```{r}
petrels=read.csv(paste0("data/censusplots.csv"))
```

```{r}
activity_rate = 0.461538 #original is 0.461538
#Aya estimated 0.34 occupancy. This is a good low number. Folger and Wayne estimated 0.66, which is a good high number. 
petrels$est_pairs=petrels$Total*activity_rate
#this is a proportion of burrows that we estimate actually contain nesting pairs. This activity rate comes from 2021 survey data and should a pretty accurate "mean activity" for the whole island
sum(petrels$est_pairs) #gives the total number of pairs that we "observed" in our plots
sum(petrels$Total)
```

```{r}
ggplot(petrels, aes(x = Total)) +
  geom_histogram(color = "black", fill = "gray60") +
  labs(title = "Actual Sample Distribution") +
  xlab("Total # of Burrows") +
  ylab("Number of Survey Plots") +
  theme_bw()
  
  
```



#simple extrapolation
```{r}
obs_area=52982.81 #area covered in our plots
vegetated_area=737259.4 #Great Duck's area that isn't coastline
wetland_area=48397.05 #area of Great Duck that is wetland and therefore not petrel habitat
habitat_area=vegetated_area-wetland_area #total petrel habitat available.

proportion_counted=obs_area/habitat_area #proportion of available habitat that we counted
extrap_factor=1/proportion_counted 

burrows_counted=sum(petrels$Total)

burrows_extrapolated=burrows_counted*extrap_factor

active_burrows_extrapolated=burrows_extrapolated*activity_rate

print(active_burrows_extrapolated)

print((burrows_counted/obs_area)*habitat_area*activity_rate)
```

```{r}
groupedpetrels <- petrels %>% 
  group_by(Plot) %>% 
  summarize(n_subplots = n())

groupedpetrels %>% 
  filter(n_subplots == 1)
```

#Bootstrap estimate

```{r}
nboot <-10000 #number of bootstrap samples
bootstrap.means <-rep(NA, nboot)
set.seed(10)
for(i in 1:nboot){
bootstrap.means[i]<- mean(sum(sample(petrels$est_pairs, size = 544,replace=TRUE)))
}
```


```{r}
est=as.data.frame(bootstrap.means)
est$extrap=est$bootstrap.means*extrap_factor#multiplying the sums of the groups of 310 plots by my extrapolation factor
```


```{r}
boothist <- ggplot(est, aes(x = extrap)) +
  geom_histogram(color = "black", fill = "gray50")+
  xlab("Population Estimate (Breeding Pairs)")+
  ylab("Number of Simulations")+
  labs(title = "Simulated Population Estimates (10,000 Reps)", subtitle = "Accounting for 46.2% Occupancy")+
  theme_bw()

print(boothist)
```

```{r}
nboot <- 10000
alpha=.05
min <- sort(est$extrap)[nboot*alpha/2]
max <- sort(est$extrap)[nboot*(1-alpha/2)]
min
max
mean <- (min + max)/2
mean

print(mean - min)
```

#Figures

```{r}
sampledist <- ggplot(petrels, aes(x = est_pairs)) + 
  geom_histogram(color ="black", fill = "gray50")+
  ylab("Number of Plots") +
  xlab("Estimated breeding pairs per plot") +
  labs(title = "2023 Sample Distribution", subtitle = "46.2% Occupancy Rate Applied") +
  theme_bw()

sampledist
```



#Percentile for loop

```{r}

nboot <- 10000
set.seed(10)


list1 <- data.frame()
for (i in 1:nboot) {
    sample <- sample(petrels$est_pairs, size = 544, replace = TRUE)
    df <- data.frame(sample)
    dfzeroes <- length(df$sample[df$sample == 0])
    summary <- df %>%
      summarize(mean = mean(sample), sum = sum(sample))
    summary$zeroes <- dfzeroes
    list1 <- rbind(list1, summary)
}

list1$extrapolation <- (list1$sum/obs_area) * habitat_area

```

```{r}
sortedlist <- list1 %>% 
  arrange(extrapolation)
```

#Area covered simulation

```{r}
nSamples = c()
estimate = c()

for(s in 1:nrow(petrels)){
  for(i in 1:30) {
  subsample = sample_n(petrels, s, 
                        replace = FALSE)
  total_est = sum(subsample$est_pairs)
  ext.est = total_est * 544/s
nSamples = append(nSamples,s)
estimate = append (estimate, ext.est)
}}
```


```{r}
extrapolations = data.frame(n_samples = nSamples, estimates = estimate)
extrapolations$extraps = extrapolations$estimates * extrap_factor

extrapolations <- extrapolations %>% 
  mutate(area = (n_samples/543)*proportion_counted)
```

```{r}

areaplot <- extrapolations %>% 
  ggplot(aes(x = n_samples, y = extraps))+
  geom_point(alpha = 0.15, fill = "gray30", color = "gray15")+
  stat_smooth(method = "lm", se = TRUE)+
  xlab("Number of 10x10m Plots Sampled")+
  ylab("Simulated Population Estimate (Breeding Pairs)")+
  theme_bw() +
  labs(title = "Simulated Population Estimates Across Sample Areas", subtitle = "30 Simulations per # of Plots Sampled")

areaplot

```

```{r}
areapropplot <- extrapolations %>% 
  ggplot(aes(x = area, y = extraps))+
  geom_point(alpha = 0.15, fill = "gray30", color = "gray15")+
  stat_smooth(method = "lm", se = TRUE)+
  xlab("Proportion of Island Covered")+
  ylab("Simulated Population Estimate (Breeding Pairs)")+
  geom_vline(xintercept = 0.00174, col = "#f8766d",size = 1.3, alpha = 0.8 ) + #Lesser
  geom_vline(xintercept = 0.01, col = "#00BFC4",size = 1.3, alpha = 0.8 ) + #Drury 1982
  geom_vline(xintercept = 0.0632, col = "#f8766d",size = 1.3, alpha = 0.8 ) + #Folger and Wayne
  geom_vline(xintercept = 0.0185, col = "#f8766d",size = 1.3, alpha = 0.8 ) + #Stockwell
  geom_vline(xintercept = 0.00574, col = "#00BFC4",size = 1.3, alpha = 0.8 ) + #Hanken
  geom_vline(xintercept = 0.00783, col = "#00BFC4",size = 1.3, alpha = 0.8) + #Shannon
  geom_vline(xintercept = 0.00570, col = "#00BFC4",size = 1.3, alpha = 0.8 ) + #Kumagai
  annotate(geom = "text", x = 0.0004, y = 50000, label = "Lesser 1977", angle = 90, size = 3) +
  annotate(geom = "text", x = 0.009, y = 50000, label = "Drury 1982 / Stowe et al. 202", angle = 90, size = 3) +
  annotate(geom = "text", x = 0.062, y = 50000, label = "Folger and Wayne 1986", angle = 90, size = 3) +
  annotate(geom = "text", x = 0.0173, y = 50000, label = "Stockwell 1995", angle = 90, size = 3)+
  annotate(geom = "text", x = 0.0045, y = 48000, label = "Hanken 2018 / Kumagai 2019", angle = 90, size = 3) +
  annotate(geom = "text", x = 0.0068, y = 50000, label = "Shannon 2018", angle = 90, size = 3)+
  labs(title = "Simulated Estimates by Proportion of Island Covered", subtitle = "30 Simulations per value of n plots") +
  theme_bw()+
  scale_color_manual(name = "Survey Method",
                     breaks = c("Plots", "Transects"),
                     values = c("Plots" = "#f8766d", "Transects" = "#00BFC4"))

areapropplot
```

```{r}
sdplot <- extrapolations %>% 
  group_by(n_samples, area) %>% 
  summarize(sd = sd(extraps)) %>% 
  ggplot(aes(x = area, y = sd)) + 
  geom_point(alpha = 0.4, fill = "gray30", color = "gray15")+
  ylab("Standard Deviation (Breeding Pairs") +
  xlab("Proportion of Island Surveyed") + 
  theme_bw() +
  labs(title = "Standard Deviation of Simulated Estimates")

sdplot

```

